"""initial PostgreSQL schema

Revision ID: 1cab686b6a16
Revises: 
Create Date: 2026-08-14 20:40:45.353937
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1cab686b6a16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('buyer_type', sa.String(length=64), nullable=False),
    sa.Column('buyer_contact_name', sa.String(length=500), nullable=False),
    sa.Column('buyer_phone', sa.String(length=64), nullable=False),
    sa.Column('buyer_email', sa.String(length=320), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('company_inn', sa.String(length=12), nullable=True),
    sa.Column('company_kpp', sa.String(length=9), nullable=True),
    sa.Column('company_legal_address', sa.String(length=1000), nullable=True),
    sa.Column('delivery_method', sa.String(length=128), nullable=False),
    sa.Column('delivery_type', sa.String(length=32), nullable=True),
    sa.Column('delivery_region', sa.String(length=500), nullable=True),
    sa.Column('delivery_city', sa.String(length=500), nullable=True),
    sa.Column('delivery_office_code', sa.String(length=128), nullable=True),
    sa.Column('delivery_postcode', sa.String(length=32), nullable=True),
    sa.Column('delivery_street', sa.String(length=500), nullable=True),
    sa.Column('delivery_house', sa.String(length=128), nullable=True),
    sa.Column('delivery_apartment', sa.String(length=128), nullable=True),
    sa.Column('recipient_contact_name', sa.String(length=500), nullable=True),
    sa.Column('recipient_phone', sa.String(length=64), nullable=True),
    sa.Column('recipient_email', sa.String(length=320), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('total_boxes', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.BigInteger(), nullable=False),
    sa.Column('products_amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('total_weight_grams', sa.BigInteger(), nullable=False),
    sa.Column('total_volume_mm3', sa.BigInteger(), nullable=False),
    sa.Column('cargo_places', sa.Integer(), nullable=False),
    sa.Column('request_fingerprint_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("delivery_method IN ('self_pickup', 'cdek')", name='ck_orders_delivery_method'),
    sa.CheckConstraint("delivery_type IS NULL OR delivery_type IN ('pickup', 'door')", name='ck_orders_delivery_type'),
    sa.CheckConstraint('cargo_places > 0', name='ck_orders_cargo_places_positive'),
    sa.CheckConstraint('length(trim(buyer_contact_name)) BETWEEN 1 AND 500', name='ck_orders_buyer_name_length'),
    sa.CheckConstraint('length(trim(buyer_email)) BETWEEN 1 AND 320', name='ck_orders_buyer_email_length'),
    sa.CheckConstraint('length(trim(buyer_phone)) BETWEEN 1 AND 64', name='ck_orders_buyer_phone_length'),
    sa.CheckConstraint('length(trim(buyer_type)) BETWEEN 1 AND 64', name='ck_orders_buyer_type_length'),
    sa.CheckConstraint('length(trim(id)) BETWEEN 1 AND 64', name='ck_orders_id_length'),
    sa.CheckConstraint('length(trim(status)) BETWEEN 1 AND 64', name='ck_orders_status_length'),
    sa.CheckConstraint('products_amount_kopecks > 0', name='ck_orders_products_amount_positive'),
    sa.CheckConstraint('total_boxes > 0', name='ck_orders_total_boxes_positive'),
    sa.CheckConstraint('total_units > 0', name='ck_orders_total_units_positive'),
    sa.CheckConstraint('total_volume_mm3 > 0', name='ck_orders_total_volume_positive'),
    sa.CheckConstraint('total_weight_grams > 0', name='ck_orders_total_weight_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_fingerprint_created', 'orders', ['request_fingerprint_digest', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('units_per_box', sa.Integer(), nullable=False),
    sa.Column('box_weight_grams', sa.BigInteger(), nullable=False),
    sa.Column('box_volume_mm3', sa.BigInteger(), nullable=False),
    sa.Column('box_length_mm', sa.Integer(), nullable=True),
    sa.Column('box_width_mm', sa.Integer(), nullable=True),
    sa.Column('box_height_mm', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(box_length_mm IS NULL AND box_width_mm IS NULL AND box_height_mm IS NULL) OR (box_length_mm > 0 AND box_width_mm > 0 AND box_height_mm > 0)', name='ck_products_dimensions_all_or_none'),
    sa.CheckConstraint('box_volume_mm3 > 0', name='ck_products_volume_positive'),
    sa.CheckConstraint('box_weight_grams > 0', name='ck_products_weight_positive'),
    sa.CheckConstraint('length(trim(name)) BETWEEN 1 AND 500', name='ck_products_name_length'),
    sa.CheckConstraint('length(trim(sku)) BETWEEN 1 AND 128', name='ck_products_sku_length'),
    sa.CheckConstraint('units_per_box > 0', name='ck_products_units_per_box_positive'),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index('idx_products_active_sku', 'products', ['active', 'sku'], unique=False)
    op.create_table('rate_limit_windows',
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('subject_digest', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('request_count > 0', name='ck_rate_limit_count_positive'),
    sa.PrimaryKeyConstraint('scope', 'subject_digest', 'window_start')
    )
    op.create_index('idx_rate_limit_window_start', 'rate_limit_windows', ['window_start'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('key_digest', sa.String(length=64), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_idempotency_expiry'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_digest')
    )
    op.create_index('idx_idempotency_expires', 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('boxes', sa.Integer(), nullable=False),
    sa.Column('units_per_box', sa.Integer(), nullable=False),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.Column('price_per_unit_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('price_per_box_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('line_amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('unit_weight_grams', sa.BigInteger(), nullable=False),
    sa.Column('unit_volume_mm3', sa.BigInteger(), nullable=False),
    sa.Column('box_length_mm', sa.Integer(), nullable=True),
    sa.Column('box_width_mm', sa.Integer(), nullable=True),
    sa.Column('box_height_mm', sa.Integer(), nullable=True),
    sa.Column('total_weight_grams', sa.BigInteger(), nullable=False),
    sa.Column('total_volume_mm3', sa.BigInteger(), nullable=False),
    sa.Column('cargo_places', sa.Integer(), nullable=False),
    sa.CheckConstraint('(box_length_mm IS NULL AND box_width_mm IS NULL AND box_height_mm IS NULL) OR (box_length_mm > 0 AND box_width_mm > 0 AND box_height_mm > 0)', name='ck_order_items_dimensions_all_or_none'),
    sa.CheckConstraint('boxes > 0', name='ck_order_items_boxes_positive'),
    sa.CheckConstraint('cargo_places > 0', name='ck_order_items_cargo_places_positive'),
    sa.CheckConstraint('line_amount_kopecks > 0', name='ck_order_items_amount_positive'),
    sa.CheckConstraint('line_number > 0', name='ck_order_items_line_number_positive'),
    sa.CheckConstraint('price_per_box_kopecks > 0', name='ck_order_items_box_price_positive'),
    sa.CheckConstraint('price_per_unit_kopecks > 0', name='ck_order_items_unit_price_positive'),
    sa.CheckConstraint('total_volume_mm3 > 0', name='ck_order_items_total_volume_positive'),
    sa.CheckConstraint('total_weight_grams > 0', name='ck_order_items_total_weight_positive'),
    sa.CheckConstraint('unit_volume_mm3 > 0', name='ck_order_items_unit_volume_positive'),
    sa.CheckConstraint('unit_weight_grams > 0', name='ck_order_items_unit_weight_positive'),
    sa.CheckConstraint('units > 0', name='ck_order_items_units_positive'),
    sa.CheckConstraint('units_per_box > 0', name='ck_order_items_units_per_box_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_number', name='uq_order_items_line_number'),
    sa.UniqueConstraint('order_id', 'sku', name='uq_order_items_sku')
    )
    op.create_index('idx_order_items_order', 'order_items', ['order_id', 'line_number'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.BigInteger(), nullable=False),
    sa.Column('locked_until', sa.BigInteger(), nullable=True),
    sa.Column('lock_token', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('succeeded_at', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("(status = 'processing' AND lock_token IS NOT NULL AND locked_until IS NOT NULL) OR status <> 'processing'", name='ck_outbox_processing_lock'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'succeeded', 'failed')", name='ck_outbox_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_outbox_attempt_count'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'order_id', name='uq_outbox_event_order')
    )
    op.create_index('idx_outbox_claim', 'outbox', ['status', 'available_at', 'locked_until', 'id'], unique=False)
    op.create_table('product_price_tiers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('product_sku', sa.String(length=128), nullable=False),
    sa.Column('min_boxes', sa.Integer(), nullable=False),
    sa.Column('max_boxes', sa.Integer(), nullable=True),
    sa.Column('price_per_unit_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('max_boxes IS NULL OR max_boxes >= min_boxes', name='ck_price_tiers_valid_range'),
    sa.CheckConstraint('min_boxes >= 1', name='ck_price_tiers_min_boxes_positive'),
    sa.CheckConstraint('price_per_unit_kopecks > 0', name='ck_price_tiers_price_positive'),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_sku', 'min_boxes', 'max_boxes', name='uq_price_tiers_range')
    )
    op.create_index('idx_product_price_tiers_lookup', 'product_price_tiers', ['product_sku', 'min_boxes', 'max_boxes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_price_tiers_lookup', table_name='product_price_tiers')
    op.drop_table('product_price_tiers')
    op.drop_index('idx_outbox_claim', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('idx_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_idempotency_expires', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index('idx_rate_limit_window_start', table_name='rate_limit_windows')
    op.drop_table('rate_limit_windows')
    op.drop_index('idx_products_active_sku', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_orders_fingerprint_created', table_name='orders')
    op.drop_index('idx_orders_created', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
